name: CI

on: [push]

jobs:
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      # Converts the markdown into HTML files so htmlproofer can work
      - name: Build the Jekyll site
        uses: ruby/setup-ruby@v1
        with:
          # https://pages.github.com/versions/
          ruby-version: '2.7'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec jekyll build

      - name: Check internal links using htmlproofer
        uses: anishathalye/proof-html@v1.4.0
        with:
          # Override the command because the GitHub Action doesn't have all the needed parameters
          entrypoint: htmlproofer
          args: _site --assume_extension --disable-external --empty-alt-ignore --url-ignore "_,#" --url-swap "^/wiki:"
