name: htmlproofer

on: [push]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Build the Jekyll site
        uses: helaili/jekyll-action@v2
        with:
          # Only build, don't publish
          build_only: true
      - name: Check HTML using htmlproofer
        uses: chabad360/htmlproofer@master
        with:
          directory: '_site'
          arguments: --assume_extension --disable-external --empty-alt-ignore --url-ignore "_,#" --url-swap "^/wiki:"
